version: "3"

services:
  gateway:
    build: ./srv/gateway
    command: "npm run dev"
    volumes:
      - ./srv/proto:/usr/src/app/proto
      - ./srv/gateway/src:/usr/src/app/srv/src
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - articles
      - users

  auth:
    build: ./srv/auth
    command: "npm run dev"
    volumes:
      - ./srv/proto:/usr/src/app/proto
      - ./srv/auth/src:/usr/src/app/srv/src
    ports:
      - "50050:50050"
    depends_on:
      - users

  users:
    build: ./srv/users
    command: "npm run dev"
    volumes:
      - ./srv/proto:/usr/src/app/proto
      - ./srv/users/src:/usr/src/app/srv/src
    ports:
      - "50051:50050"

  articles:
    build: ./srv/articles
    command: "npm run dev"
    volumes:
      - ./srv/proto:/usr/src/app/proto
      - ./srv/articles/src:/usr/src/app/srv/src
    ports:
      - "50052:50050"

  comments:
    build: ./srv/comments
    command: "npm run dev"
    volumes:
      - ./srv/proto:/usr/src/app/proto
      - ./srv/comments/src:/usr/src/app/srv/src
    ports:
      - "50053:50050"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
