version: "3"

# Volumes
volumes:
  mongodb:

# Services
services:
  gateway:
    build:
      context: ../../srv/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ../../srv/proto:/usr/src/app/proto
      - ../../srv/gateway/src:/usr/src/app/srv/src
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - articles
      - users

  auth:
    build:
      context: ../../srv/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ../../srv/proto:/usr/src/app/proto
      - ../../srv/auth/src:/usr/src/app/srv/src
    ports:
      - "50050:50050"
    depends_on:
      - users
      - mongo

  users:
    build:
      context: ../../srv/users
      dockerfile: Dockerfile.dev
    volumes:
      - ../../srv/proto:/usr/src/app/proto
      - ../../srv/users/src:/usr/src/app/srv/src
    ports:
      - "50051:50050"
    depends_on:
      - mongo

  articles:
    build:
      context: ../../srv/articles
      dockerfile: Dockerfile.dev
    volumes:
      - ../../srv/proto:/usr/src/app/proto
      - ../../srv/articles/src:/usr/src/app/srv/src
    ports:
      - "50052:50050"
    depends_on:
      - mongo

  comments:
    build:
      context: ../../srv/comments
      dockerfile: Dockerfile.dev
    volumes:
      - ../../srv/proto:/usr/src/app/proto
      - ../../srv/comments/src:/usr/src/app/srv/src
    ports:
      - "50053:50050"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
