version: "3"

# Volumes
volumes:
  mongodb:

# Services
services:
  gateway:
    build:
      context: ../../src
      dockerfile: services/gateway/Dockerfile
      args:
        SERVICE: gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth
      - articles
      - users

  auth:
    build:
      context: ../../src
      dockerfile: services/auth/Dockerfile
      args:
        SERVICE: auth
    ports:
      - "50050:50050"
    depends_on:
      - users
      - mongo

  users:
    build:
      context: ../../src
      dockerfile: services/users/Dockerfile
      args:
        SERVICE: users
    ports:
      - "50051:50050"
    depends_on:
      - mongo

  articles:
    build:
      context: ../../src
      dockerfile: services/articles/Dockerfile
      args:
        SERVICE: articles
    ports:
      - "50052:50050"
    depends_on:
      - mongo

  comments:
    build:
      context: ../../src
      dockerfile: services/comments/Dockerfile
      args:
        SERVICE: comments
    ports:
      - "50053:50050"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
